#!/bin/sh

# bash script to automatically add, commit, push trst code
# args: commit message

echo "git add -A"
git add .
echo "git commit -m \"$1\""
git commit -m "$1"
echo "git push"
git push
echo "git status"
git status
